networks:
  traefik:
    external: true

services:
  web-marriage:
    container_name: web-marriage
    restart: unless-stopped
    build:
     context: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-marriage.rule=Host(`scotex.tech`)"
      - "traefik.http.routers.web-marriage.entrypoints=websecure"
      - "traefik.http.routers.web-marriage.tls.certresolver=lets-encrypt"
      - "traefik.http.services.web-marriage.loadbalancer.server.port=80"
    networks:
      - traefik